#!/usr/bin/env node
/**
 * gen-sitemap.mjs — T-005.
 *
 * The sitemap and robots.txt are generated from `src/lib/siteConfig.js`, so
 * the origin exists in exactly one place in the repository. `lastmod` comes
 * from `git log -1 --format=%cI` rather than from `new Date()`: a sitemap that
 * claims every page changed on every build teaches crawlers to ignore the
 * field, which is the opposite of the point.
 *
 * Runs in `prebuild`, writing into `public/` so Vite copies the result.
 */
import { writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SITE_URL, ROUTES, absolute } from '../src/lib/siteConfig.js'

const PUBLIC = fileURLToPath(new URL('../public', import.meta.url))

/** The last commit date, ISO-8601, date part only. Falls back to today. */
function lastCommitDate() {
  try {
    const iso = execSync('git log -1 --format=%cI', { encoding: 'utf8' }).trim()
    if (iso) return iso.slice(0, 10)
  } catch {
    /* not a git checkout (a tarball build, say) — today is the honest answer */
  }
  return new Date().toISOString().slice(0, 10)
}

const lastmod = lastCommitDate()

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  (r) => `  <url>
    <loc>${absolute(r.path)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`
).join('\n')}
</urlset>
`

const robots = `# Generated by scripts/gen-sitemap.mjs — edit src/lib/siteConfig.js instead.
User-agent: *
Allow: /

Sitemap: ${absolute('/sitemap.xml')}
`

writeFileSync(join(PUBLIC, 'sitemap.xml'), sitemap, 'utf8')
writeFileSync(join(PUBLIC, 'robots.txt'), robots, 'utf8')

console.log(`sitemap: ${ROUTES.length} route(s) at ${SITE_URL}, lastmod ${lastmod}`)
